version: 2
jobs:
  dist:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - run:
          name: Install nfpm, rpmbuild
          command: |
            sudo make -f Makefile.tools nfpm-debian rpmbuild-debian
      - run:
          name: Make distributables
          command: |
            make -f Makefile.release dist
      - persist_to_workspace:
          root: .
          paths: ['dist/*']

  publish:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run:
          name: Release
          command: |
            make -f Makefile.release publish

workflows:
  version: 2
  dist-publish:
    jobs:
      - dist:
          # needed to ensure dist happens on tag events
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - dist
          filters:
            # never publish from a branch event
            branches:
              ignore: /.*/
            # release only on tag push events like vX[.Y.Z...][-whatever]
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/
